# Generated by Django 5.2.15 on 2026-08-17 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('GRANT_VIP', 'Grant VIP'), ('REVOKE_VIP', 'Revoke VIP'), ('SUSPEND_USER', 'Suspend User'), ('ACTIVATE_USER', 'Activate User'), ('SUSPEND_BOT', 'Suspend Bot'), ('RESUME_BOT', 'Resume Bot'), ('RESTART_BOT', 'Restart Bot'), ('GRANT_DIAMONDS', 'Grant Diamonds'), ('ADJUST_BALANCE', 'Adjust Balance'), ('APPROVE_PAYMENT', 'Approve Payment'), ('REJECT_PAYMENT', 'Reject Payment'), ('CHANGE_PLAN', 'Change Plan'), ('CREATE_MARKET_ITEM', 'Create Market Item'), ('UPDATE_MARKET_ITEM', 'Update Market Item'), ('SYSTEM_CONFIG_CHANGE', 'System Config Change')], db_index=True, max_length=50)),
                ('target_type', models.CharField(db_index=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(default='SUCCESS', max_length=20)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='common_admi_action_273de2_idx'), models.Index(fields=['target_type', 'target_id'], name='common_admi_target__c619a3_idx'), models.Index(fields=['admin', 'action'], name='common_admi_admin_i_cce253_idx')],
            },
        ),
    ]
