# Generated by Django 5.2.15 on 2026-08-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Whether the user account is suspended by administrator.'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'SuperAdmin'), ('ADMIN', 'Admin'), ('MODERATOR', 'Moderator'), ('SUPPORT', 'Support'), ('USER', 'User')], db_index=True, default='USER', help_text='User authorization role on the platform.', max_length=20),
        ),
    ]
