# Generated by Django 5.2.15 on 2026-08-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_suspended_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_owner',
            field=models.BooleanField(db_index=True, default=False, help_text='Platform Owner account with unrestricted privileges (e.g. @ismoilo9).'),
        ),
    ]
