# Generated by Django 5.2.15 on 2026-08-18 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_platform_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_name',
            field=models.CharField(blank=True, default='', help_text='Name of the Telegram Group managed by this admin.', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_admin',
            field=models.ForeignKey(blank=True, help_text='Parent Group Owner if this account is a co-admin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'SuperAdmin'), ('ADMIN', 'Group Owner / Admin'), ('MODERATOR', 'Group Co-Admin / Moderator'), ('SUPPORT', 'Support'), ('USER', 'User')], db_index=True, default='USER', help_text='User authorization role on the platform.', max_length=20),
        ),
    ]
