# Generated by Django 5.2.15 on 2026-08-17 18:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('telegram_username', models.CharField(db_index=True, max_length=255)),
                ('telegram_bot_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Validation'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('SUSPENDED', 'Suspended'), ('ERROR', 'Error'), ('DELETED', 'Deleted')], db_index=True, default='PENDING', max_length=20)),
                ('runtime_status', models.CharField(choices=[('OFFLINE', 'Offline'), ('STARTING', 'Starting'), ('RUNNING', 'Running'), ('STOPPING', 'Stopping'), ('ERROR', 'Runtime Error')], db_index=True, default='OFFLINE', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('night_duration_seconds', models.PositiveIntegerField(default=60)),
                ('day_duration_seconds', models.PositiveIntegerField(default=120)),
                ('voting_duration_seconds', models.PositiveIntegerField(default=60)),
                ('allow_custom_roles', models.BooleanField(default=False)),
                ('show_roles_on_death', models.BooleanField(default=True)),
                ('extra_settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BotCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encrypted_token', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
