# Generated by Django 5.2.15 on 2026-08-17 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='bots.bot'),
        ),
        migrations.AddField(
            model_name='botcredential',
            name='bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='bots.bot'),
        ),
        migrations.AlterUniqueTogether(
            name='bot',
            unique_together={('owner', 'telegram_username')},
        ),
    ]
