# Generated by Django 5.2.15 on 2026-08-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(choices=[('STANDARD', 'Standart (Classic)'), ('SUPER', 'Super (Advanced)'), ('MEGA', 'Mega (Univers Pro)')], db_index=True, default='STANDARD', max_length=20),
        ),
    ]
