# Generated by Django 5.2.15 on 2026-08-28 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_bot_bot_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(default='Telegram Guruh', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('owner_telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, default='', max_length=255)),
                ('owner_username', models.CharField(blank=True, default='', max_length=255)),
                ('total_games_played', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_groups', to='bots.bot')),
            ],
            options={
                'ordering': ['-last_active_at'],
                'unique_together': {('bot', 'chat_id')},
            },
        ),
    ]
