# Generated by Django 5.2.15 on 2026-08-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_botgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='botgroup',
            name='cabinet_login',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='botgroup',
            name='cabinet_password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='botgroup',
            name='group_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
