# Generated by Django 5.2.15 on 2026-09-09 08:50

import django.db.models.deletion
from django.db import migrations, models


def merge_duplicate_bot_groups(apps, schema_editor):
    BotGroup = apps.get_model('bots', 'BotGroup')
    from django.db.models import Count
    # Find duplicate chat_ids
    duplicates = (
        BotGroup.objects.values('chat_id')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )
    for dup in duplicates:
        cid = dup['chat_id']
        groups = list(BotGroup.objects.filter(chat_id=cid).order_by('-last_active_at', '-created_at'))
        if not groups:
            continue
        primary = groups[0]
        # Merge stats & non-empty fields from duplicate records
        for other in groups[1:]:
            if not primary.cabinet_login and other.cabinet_login:
                primary.cabinet_login = other.cabinet_login
            if not primary.cabinet_password and other.cabinet_password:
                primary.cabinet_password = other.cabinet_password
            if not primary.owner_telegram_id and other.owner_telegram_id:
                primary.owner_telegram_id = other.owner_telegram_id
                primary.owner_name = other.owner_name
                primary.owner_username = other.owner_username
            if not primary.group_settings and other.group_settings:
                primary.group_settings = other.group_settings
            primary.total_games_played += other.total_games_played
            other.delete()
        primary.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_botgroup_cabinet_login_botgroup_cabinet_password_and_more'),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_bot_groups, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='botgroup',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='botgroup',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_groups', to='bots.bot'),
        ),
        migrations.AlterField(
            model_name='botgroup',
            name='chat_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
