# Generated by Django 5.2.15 on 2026-09-09 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


def populate_initial_bot_users(apps, schema_editor):
    BotUser = apps.get_model('bots', 'BotUser')
    try:
        Player = apps.get_model('games', 'Player')
        for p in Player.objects.select_related('game__bot').all():
            if p.telegram_user_id:
                bot_obj = getattr(p.game, 'bot', None)
                BotUser.objects.get_or_create(
                    bot=bot_obj,
                    telegram_id=p.telegram_user_id,
                    defaults={
                        'username': p.username or '',
                        'first_name': p.display_name or '',
                        'is_bot_started': True,
                    }
                )
    except Exception:
        pass
    try:
        PlayerProfile = apps.get_model('stats', 'PlayerProfile')
        for prof in PlayerProfile.objects.all():
            if prof.telegram_id:
                BotUser.objects.get_or_create(
                    bot=None,
                    telegram_id=prof.telegram_id,
                    defaults={
                        'username': prof.telegram_username or '',
                        'first_name': prof.first_name or '',
                        'last_name': prof.last_name or '',
                        'is_bot_started': True,
                    }
                )
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_alter_botgroup_chat_id_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_bot_started', models.BooleanField(default=True, help_text='User pressed /start in private chat')),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bots.bot')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['telegram_id', 'is_bot_started'], name='bots_botuse_telegra_2132c6_idx'), models.Index(fields=['username'], name='bots_botuse_usernam_3c769a_idx')],
                'unique_together': {('bot', 'telegram_id')},
            },
        ),
        migrations.RunPython(populate_initial_bot_users, migrations.RunPython.noop),
    ]
