# Generated by Django 5.2.15 on 2026-08-17 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_icon', models.CharField(default='🏆', max_length=20)),
                ('category', models.CharField(choices=[('VICTORY', 'Victories & Wins'), ('ROLE_MASTERY', 'Role Mastery'), ('SURVIVAL', 'Survival'), ('WEALTH', 'Wealth & Collection'), ('SOCIAL', 'Social & Tournaments')], default='VICTORY', max_length=30)),
                ('diamond_reward', models.PositiveIntegerField(default=0)),
                ('coin_reward', models.PositiveIntegerField(default=0)),
                ('target_count', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'target_count'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('custom_title', models.CharField(blank=True, max_length=100)),
                ('language_code', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=10)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('games_lost', models.PositiveIntegerField(default=0)),
                ('mafia_wins', models.PositiveIntegerField(default=0)),
                ('civilian_wins', models.PositiveIntegerField(default=0)),
                ('doctor_saves', models.PositiveIntegerField(default=0)),
                ('detective_investigations', models.PositiveIntegerField(default=0)),
                ('successful_kills', models.PositiveIntegerField(default=0)),
                ('successful_votes', models.PositiveIntegerField(default=0)),
                ('survival_count', models.PositiveIntegerField(default=0)),
                ('best_win_streak', models.PositiveIntegerField(default=0)),
                ('current_win_streak', models.PositiveIntegerField(default=0)),
                ('mvp_count', models.PositiveIntegerField(default=0)),
                ('protection_count', models.PositiveIntegerField(default=0)),
                ('investigation_count', models.PositiveIntegerField(default=0)),
                ('voting_count', models.PositiveIntegerField(default=0)),
                ('doctor_count', models.PositiveIntegerField(default=0)),
                ('mask_count', models.PositiveIntegerField(default=0)),
                ('defense_count', models.PositiveIntegerField(default=0)),
                ('player_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='stats.playerprofile')),
            ],
            options={
                'ordering': ['-games_won', '-games_played'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.achievement')),
                ('player_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_achievements', to='stats.playerprofile')),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('player_profile', 'achievement')},
            },
        ),
    ]
