# Generated by Django 5.2.15 on 2026-08-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='is_platform_owner',
            field=models.BooleanField(db_index=True, default=False, help_text='Platform Owner status (e.g. @ismoilo9) granting unrestricted features and VIP Diamond.'),
        ),
    ]
