# Generated by Django 5.2.15 on 2026-08-26 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_playerprofile_is_platform_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCouple',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1_id', models.BigIntegerField(db_index=True)),
                ('user1_name', models.CharField(default='', max_length=255)),
                ('user2_id', models.BigIntegerField(db_index=True)),
                ('user2_name', models.CharField(default='', max_length=255)),
                ('chat_id', models.BigIntegerField(blank=True, help_text='Group chat where couple was formed', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': "O'yinchi Parasi",
                'verbose_name_plural': "O'yinchilar Paralari",
                'ordering': ['-created_at'],
            },
        ),
    ]
