# Generated by Django 5.2.15 on 2026-09-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_playercouple'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='is_channel_bonus_claimed',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether player has received the 2x dollar bonus for joining @MafiaBotFather channel.'),
        ),
    ]
