# Generated by Django 5.2.15 on 2026-08-17 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0002_initial'),
        ('games', '0003_phase3_roles_configuration'),
        ('templates', '0002_phase3_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTRATION', 'Registration Open'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('max_players', models.PositiveSmallIntegerField(default=24)),
                ('players_per_game', models.PositiveSmallIntegerField(default=6, help_text='How many participants per individual game in a round.')),
                ('total_rounds', models.PositiveSmallIntegerField(default=3)),
                ('current_round', models.PositiveSmallIntegerField(default=0)),
                ('configuration_data', models.JSONField(default=dict, help_text='Frozen game configuration used for all tournament games.')),
                ('scoring_config', models.JSONField(default=dict, help_text='Scoring rules: {participation: 1, survival: 1, winning_faction: 3, mafia_elimination: 1, final_survivor: 2}')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='bots.bot')),
                ('game_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='templates.gametemplate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_user_id', models.BigIntegerField(db_index=True)),
                ('display_name', models.CharField(default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('games_played', models.PositiveSmallIntegerField(default=0)),
                ('games_won', models.PositiveSmallIntegerField(default=0)),
                ('games_lost', models.PositiveSmallIntegerField(default=0)),
                ('kills', models.PositiveSmallIntegerField(default=0)),
                ('survival_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn'), ('DISQUALIFIED', 'Disqualified')], db_index=True, default='ACTIVE', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-score', '-games_won', '-survival_count', 'telegram_user_id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TournamentGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_number', models.PositiveSmallIntegerField(default=1, help_text='Which group within this round (e.g. Group A=1, Group B=2).')),
                ('score_applied', models.BooleanField(default=False, help_text="True after TournamentScoringService has processed this game's result.")),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_game', to='games.game')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_games', to='tournaments.tournamentround')),
            ],
            options={
                'ordering': ['group_number'],
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['owner', 'status'], name='tournaments_owner_i_7a28b4_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status', 'created_at'], name='tournaments_status_c9aba7_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['tournament', 'status', '-score'], name='tournaments_tournam_40d8cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together={('tournament', 'telegram_user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentround',
            unique_together={('tournament', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentgame',
            unique_together={('round', 'group_number')},
        ),
    ]
