# Generated by Django 5.2.15 on 2026-08-17 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='gametemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='gametemplate',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='gametemplate',
            name='is_official',
        ),
        migrations.RemoveField(
            model_name='gametemplate',
            name='settings',
        ),
        migrations.AddField(
            model_name='bottemplate',
            name='default_game_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_templates', to='templates.gametemplate'),
        ),
        migrations.AddField(
            model_name='bottemplate',
            name='game_mode',
            field=models.CharField(choices=[('CLASSIC', 'Classic'), ('QUICK', 'Quick'), ('CUSTOM', 'Custom'), ('TOURNAMENT', 'Tournament')], default='CLASSIC', max_length=20),
        ),
        migrations.AddField(
            model_name='bottemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gametemplate',
            name='configuration_data',
            field=models.JSONField(default=dict, help_text='Serialized game configuration: minimum_players, maximum_players, night_duration, discussion_duration, voting_duration, allow_self_vote, allow_self_protection, reveal_role_on_elimination, tie_behavior, mafia_vote_mode, automatic_phase_transition, day_discussion_enabled'),
        ),
        migrations.AddField(
            model_name='gametemplate',
            name='game_mode',
            field=models.CharField(choices=[('CLASSIC', 'Classic'), ('QUICK', 'Quick'), ('CUSTOM', 'Custom'), ('TOURNAMENT', 'Tournament')], default='CLASSIC', max_length=20),
        ),
        migrations.AddField(
            model_name='gametemplate',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='null = system template, non-null = user-owned template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gametemplate',
            name='role_distribution_data',
            field=models.JSONField(default=list, help_text='List of role distribution rules: [{role_code, role_name, team, min_count, max_count, distribution_type}, ...]'),
        ),
        migrations.AddField(
            model_name='gametemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gametemplate',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='Original template this was duplicated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='templates.gametemplate'),
        ),
        migrations.AddField(
            model_name='gametemplate',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DRAFT', 'Draft')], db_index=True, default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='gametemplate',
            name='template_type',
            field=models.CharField(choices=[('SYSTEM', 'System Template'), ('USER', 'User Template')], db_index=True, default='USER', max_length=10),
        ),
        migrations.AddField(
            model_name='gametemplate',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gametemplate',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private (Owner Only)'), ('PUBLIC', 'Public (All Users)')], db_index=True, default='PRIVATE', max_length=10),
        ),
        migrations.AlterField(
            model_name='bottemplate',
            name='config_preset',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bottemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gametemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='gametemplate',
            index=models.Index(fields=['owner', 'status', 'visibility'], name='templates_g_owner_i_76dd91_idx'),
        ),
        migrations.AddIndex(
            model_name='gametemplate',
            index=models.Index(fields=['template_type', 'visibility', 'status'], name='templates_g_templat_d9a929_idx'),
        ),
    ]
