# Generated by Django 5.2.15 on 2026-08-17 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('team', models.CharField(choices=[('CIVILIAN', 'Civilian'), ('MAFIA', 'Mafia'), ('NEUTRAL', 'Neutral')], default='CIVILIAN', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.BigIntegerField(db_index=True, help_text='Telegram Group Chat ID')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for Players'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], db_index=True, default='WAITING', max_length=20)),
                ('winner_team', models.CharField(blank=True, choices=[('CIVILIAN', 'Civilian'), ('MAFIA', 'Mafia'), ('NEUTRAL', 'Neutral')], max_length=20, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='bots.bot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_user_id', models.BigIntegerField(db_index=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_alive', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.game')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='games.role')),
            ],
            options={
                'unique_together': {('game', 'telegram_user_id')},
            },
        ),
    ]
