# Generated by Django 5.2.15 on 2026-08-17 19:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('MAFIA_KILL', 'Mafia Kill'), ('DOCTOR_PROTECT', 'Doctor Protect'), ('DETECTIVE_INVESTIGATE', 'Detective Investigate')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='player',
            old_name='full_name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='game',
            name='phase',
            field=models.CharField(choices=[('WAITING', 'Waiting for Players'), ('STARTING', 'Starting'), ('NIGHT', 'Night'), ('DAY', 'Day'), ('DISCUSSION', 'Discussion'), ('VOTING', 'Voting'), ('ELIMINATION', 'Elimination'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], db_index=True, default='WAITING', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='phase_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='eliminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='eliminated_reason',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for Players'), ('STARTING', 'Starting'), ('NIGHT', 'Night'), ('DAY', 'Day'), ('DISCUSSION', 'Discussion'), ('VOTING', 'Voting'), ('ELIMINATION', 'Elimination'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], db_index=True, default='WAITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_alive',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('MAFIA', 'Mafia'), ('DOCTOR', 'Doctor'), ('DETECTIVE', 'Detective'), ('DON', 'Don')], max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['bot', 'chat_id', 'status'], name='games_game_bot_id_413b2e_idx'),
        ),
        migrations.AddField(
            model_name='nightaction',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_actions', to='games.player'),
        ),
        migrations.AddField(
            model_name='nightaction',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='night_actions', to='games.game'),
        ),
        migrations.AddField(
            model_name='nightaction',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_actions', to='games.player'),
        ),
        migrations.AddField(
            model_name='vote',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='games.game'),
        ),
        migrations.AddField(
            model_name='vote',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_votes', to='games.player'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_votes', to='games.player'),
        ),
        migrations.AddIndex(
            model_name='nightaction',
            index=models.Index(fields=['game', 'round', 'action_type'], name='games_night_game_id_5e74db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nightaction',
            unique_together={('game', 'round', 'actor')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['game', 'round'], name='games_vote_game_id_f70109_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('game', 'round', 'voter')},
        ),
    ]
