# Generated by Django 5.2.15 on 2026-08-17 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_initial'),
        ('games', '0002_nightaction_vote_alter_player_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration_name', models.CharField(default='Default', max_length=255)),
                ('game_mode', models.CharField(choices=[('CLASSIC', 'Classic'), ('QUICK', 'Quick'), ('CUSTOM', 'Custom'), ('TOURNAMENT', 'Tournament')], default='CLASSIC', max_length=20)),
                ('minimum_players', models.PositiveSmallIntegerField(default=4)),
                ('maximum_players', models.PositiveSmallIntegerField(default=20)),
                ('night_duration', models.PositiveIntegerField(default=60)),
                ('discussion_duration', models.PositiveIntegerField(default=120)),
                ('voting_duration', models.PositiveIntegerField(default=60)),
                ('allow_self_vote', models.BooleanField(default=False)),
                ('allow_self_protection', models.BooleanField(default=False)),
                ('reveal_role_on_elimination', models.BooleanField(default=True)),
                ('tie_behavior', models.CharField(choices=[('NO_ELIMINATION', 'No Elimination on Tie'), ('RANDOM', 'Random Elimination on Tie')], default='NO_ELIMINATION', max_length=20)),
                ('mafia_vote_mode', models.CharField(choices=[('MAJORITY', 'Majority Vote Required'), ('ANY', 'Any Single Mafia Can Choose')], default='ANY', max_length=20)),
                ('automatic_phase_transition', models.BooleanField(default=True)),
                ('day_discussion_enabled', models.BooleanField(default=True)),
                ('role_distribution_snapshot', models.JSONField(default=list, help_text='Frozen list of {role_code, role_name, team, min_count, max_count, distribution_type}')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default Configuration', max_length=255)),
                ('game_mode', models.CharField(choices=[('CLASSIC', 'Classic'), ('QUICK', 'Quick'), ('CUSTOM', 'Custom'), ('TOURNAMENT', 'Tournament')], default='CLASSIC', max_length=20)),
                ('minimum_players', models.PositiveSmallIntegerField(default=4)),
                ('maximum_players', models.PositiveSmallIntegerField(default=20)),
                ('night_duration', models.PositiveIntegerField(default=60)),
                ('discussion_duration', models.PositiveIntegerField(default=120)),
                ('voting_duration', models.PositiveIntegerField(default=60)),
                ('allow_self_vote', models.BooleanField(default=False)),
                ('allow_self_protection', models.BooleanField(default=False)),
                ('reveal_role_on_elimination', models.BooleanField(default=True)),
                ('tie_behavior', models.CharField(choices=[('NO_ELIMINATION', 'No Elimination on Tie'), ('RANDOM', 'Random Elimination on Tie')], default='NO_ELIMINATION', max_length=20)),
                ('mafia_vote_mode', models.CharField(choices=[('MAJORITY', 'Majority Vote Required'), ('ANY', 'Any Single Mafia Can Choose')], default='ANY', max_length=20)),
                ('allow_player_rejoin', models.BooleanField(default=False)),
                ('automatic_phase_transition', models.BooleanField(default=True)),
                ('day_discussion_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleAbility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ability_type', models.CharField(choices=[('KILL', 'Kill'), ('PROTECT', 'Protect'), ('INVESTIGATE', 'Investigate'), ('NONE', 'None (Passive)')], default='NONE', max_length=20)),
                ('phase', models.CharField(choices=[('NIGHT', 'Night'), ('DAY', 'Day'), ('ANY', 'Any Phase')], default='NIGHT', max_length=10)),
                ('target_required', models.BooleanField(default=True)),
                ('uses_per_game', models.PositiveSmallIntegerField(default=0, help_text='0 = unlimited uses per game.')),
                ('cooldown_rounds', models.PositiveSmallIntegerField(default=0, help_text='0 = no cooldown between rounds.')),
                ('allowed_targets', models.CharField(choices=[('CIVILIAN', 'Civilian'), ('MAFIA', 'Mafia'), ('NEUTRAL', 'Neutral'), ('ANY', 'Any Living Player')], default='ANY', help_text='Which faction can be targeted. ANY = all living players.', max_length=20)),
            ],
            options={
                'ordering': ['phase', 'ability_type'],
            },
        ),
        migrations.CreateModel(
            name='RoleDistributionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distribution_type', models.CharField(choices=[('EXACT', 'Exact Count'), ('RANGE', 'Range (min-max)'), ('PERCENTAGE', 'Percentage of Players')], default='EXACT', max_length=20)),
                ('min_count', models.PositiveSmallIntegerField(default=1)),
                ('max_count', models.PositiveSmallIntegerField(default=1)),
                ('percentage', models.PositiveSmallIntegerField(default=0)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Processing order; higher priority roles are allocated first.')),
            ],
            options={
                'ordering': ['-priority', 'role__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['priority', 'name']},
        ),
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.SlugField(default='', help_text="Unique machine-readable identifier (e.g. 'mafia', 'doctor')."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='True for built-in platform roles that cannot be deleted.'),
        ),
        migrations.AddField(
            model_name='role',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='null = system role, non-null = user-owned custom role', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display and processing order priority.'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('code', 'owner')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['owner', 'is_active'], name='games_role_owner_i_f8a7e2_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_system', 'is_active'], name='games_role_is_syst_72b903_idx'),
        ),
        migrations.AddField(
            model_name='configurationsnapshot',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_snapshot', to='games.game'),
        ),
        migrations.AddField(
            model_name='gameconfiguration',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_configurations', to='bots.bot'),
        ),
        migrations.AddField(
            model_name='gameconfiguration',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='game_configuration',
            field=models.ForeignKey(blank=True, help_text='Optional configuration used before game start. Snapshot is created on start.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.gameconfiguration'),
        ),
        migrations.AddField(
            model_name='roleability',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='games.role'),
        ),
        migrations.AddField(
            model_name='roledistributionrule',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_rules', to='games.gameconfiguration'),
        ),
        migrations.AddField(
            model_name='roledistributionrule',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_rules', to='games.role'),
        ),
        migrations.AddIndex(
            model_name='gameconfiguration',
            index=models.Index(fields=['owner', 'game_mode'], name='games_gamec_owner_i_0665b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roledistributionrule',
            unique_together={('configuration', 'role')},
        ),
    ]
