# Generated by Django 5.2.15 on 2026-08-17 20:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_phase3_roles_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsnapshot',
            name='custom_theme',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='configurationsnapshot',
            name='day_media_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='configurationsnapshot',
            name='elimination_media_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='configurationsnapshot',
            name='night_media_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='configurationsnapshot',
            name='victory_media_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='gameconfiguration',
            name='custom_theme',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='gameconfiguration',
            name='day_media_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='gameconfiguration',
            name='elimination_media_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='gameconfiguration',
            name='night_media_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='gameconfiguration',
            name='victory_media_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='configurationsnapshot',
            name='game_mode',
            field=models.CharField(choices=[('CLASSIC', 'Classic'), ('BLOODY', 'Bloody Mafia'), ('BLOODY_MEGA', 'Bloody Mafia Mega'), ('FAST', 'Fast'), ('QUICK', 'Quick'), ('CUSTOM', 'Custom'), ('TOURNAMENT', 'Tournament')], default='CLASSIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameconfiguration',
            name='game_mode',
            field=models.CharField(choices=[('CLASSIC', 'Classic'), ('BLOODY', 'Bloody Mafia'), ('BLOODY_MEGA', 'Bloody Mafia Mega'), ('FAST', 'Fast'), ('QUICK', 'Quick'), ('CUSTOM', 'Custom'), ('TOURNAMENT', 'Tournament')], default='CLASSIC', max_length=20),
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('GAME_CREATED', 'Game Created'), ('PLAYER_JOINED', 'Player Joined'), ('PLAYER_LEFT', 'Player Left'), ('GAME_STARTED', 'Game Started'), ('ROLE_ASSIGNED', 'Role Assigned'), ('NIGHT_STARTED', 'Night Started'), ('NIGHT_ACTION', 'Night Action'), ('NIGHT_RESOLVED', 'Night Resolved'), ('DAY_STARTED', 'Day Started'), ('DISCUSSION_STARTED', 'Discussion Started'), ('VOTE_STARTED', 'Vote Started'), ('VOTE_CAST', 'Vote Cast'), ('VOTE_RESOLVED', 'Vote Resolved'), ('PLAYER_ELIMINATED', 'Player Eliminated'), ('ROUND_COMPLETED', 'Round Completed'), ('GAME_FINISHED', 'Game Finished'), ('GAME_CANCELED', 'Game Canceled')], db_index=True, max_length=40)),
                ('round', models.PositiveIntegerField(default=1)),
                ('phase', models.CharField(default='WAITING', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_events', to='games.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='games.game')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_events', to='games.player')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['game', 'event_type', 'round'], name='games_gamee_game_id_ea9ac2_idx'), models.Index(fields=['game', 'created_at'], name='games_gamee_game_id_e5de00_idx')],
            },
        ),
    ]
