# Generated by Django 5.2.15 on 2026-08-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_configurationsnapshot_custom_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lobby_message_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram Message ID of the active lobby message in group chat', null=True),
        ),
    ]
