# Generated by Django 5.2.15 on 2026-08-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_lobby_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='player',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner_team',
            field=models.CharField(blank=True, choices=[('CIVILIAN', 'Civilian'), ('MAFIA', 'Mafia'), ('NEUTRAL', 'Neutral'), ('SOLO', 'Solo'), ('ZOMBIE', 'Zombie')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nightaction',
            name='action_type',
            field=models.CharField(choices=[('MAFIA_KILL', 'Mafia Kill'), ('DOCTOR_PROTECT', 'Doctor Protect'), ('DETECTIVE_INVESTIGATE', 'Detective Investigate'), ('DETECTIVE_SHOOT', 'Detective Shoot'), ('QOTIL_KILL', 'Qotil Kill'), ('KEZUVCHI_VISIT', 'Kezuvchi Visit'), ('DAYDI_VISIT', 'Daydi Visit'), ('ADVOKAT_PROTECT', 'Advokat Protect'), ('UBIYTSA_KILL', 'Ubiytsa Kill'), ('TUZOQCHI_TRAP', 'Tuzoqchi Trap'), ('ZOMBI_BITE', 'Zombi Bite'), ('KIMYOGAR_POTION', 'Kimyogar Potion'), ('AXMOQ_VISIT', 'Axmoq Visit'), ('BUQALAMUN_MORPH', 'Buqalamun Morph'), ('RAIS_GIFT', 'Rais Gift'), ('JOKER_BOXES', 'Joker Boxes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='team',
            field=models.CharField(choices=[('CIVILIAN', 'Civilian'), ('MAFIA', 'Mafia'), ('NEUTRAL', 'Neutral'), ('SOLO', 'Solo'), ('ZOMBIE', 'Zombie')], default='CIVILIAN', max_length=20),
        ),
        migrations.AlterField(
            model_name='roleability',
            name='allowed_targets',
            field=models.CharField(choices=[('CIVILIAN', 'Civilian'), ('MAFIA', 'Mafia'), ('NEUTRAL', 'Neutral'), ('SOLO', 'Solo'), ('ZOMBIE', 'Zombie'), ('ANY', 'Any Living Player')], default='ANY', help_text='Which faction can be targeted. ANY = all living players.', max_length=20),
        ),
    ]
