# Generated by Django 5.2.15 on 2026-09-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_nightaction_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='health',
            field=models.PositiveIntegerField(default=100, help_text='Player health percentage'),
        ),
    ]
