# Generated by Django 5.2.15 on 2026-09-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_player_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('CLASSIC', 'Classic'), ('TEAM', 'Team')], db_index=True, default='CLASSIC', max_length=20),
        ),
    ]
