# Generated by Django 5.2.15 on 2026-09-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightaction',
            name='action_type',
            field=models.CharField(choices=[('MAFIA_KILL', 'Mafia Kill'), ('DOCTOR_PROTECT', 'Doctor Protect'), ('DETECTIVE_INVESTIGATE', 'Detective Investigate'), ('DETECTIVE_SHOOT', 'Detective Shoot'), ('QOTIL_KILL', 'Qotil Kill'), ('KEZUVCHI_VISIT', 'Kezuvchi Visit'), ('DAYDI_VISIT', 'Daydi Visit'), ('ADVOKAT_PROTECT', 'Advokat Protect'), ('UBIYTSA_KILL', 'Ubiytsa Kill'), ('TUZOQCHI_TRAP', 'Tuzoqchi Trap'), ('ZOMBI_BITE', 'Zombi Bite'), ('KIMYOGAR_POTION', 'Kimyogar Potion'), ('AXMOQ_VISIT', 'Axmoq Visit'), ('BUQALAMUN_MORPH', 'Buqalamun Morph'), ('RAIS_GIFT', 'Rais Gift'), ('JOKER_BOXES', 'Joker Boxes'), ('AFERIST_STEAL', 'Aferist Steal'), ('GAZABKOR_MARK', 'Gazabkor Mark'), ('SEHRGAR_CHOICE', 'Sehrgar Choice'), ('JURNALIST_INVESTIGATE', 'Jurnalist Investigate'), ('SOTQIN_CHECK', 'Sotqin Check'), ('ROBINGUD_SHOOT', 'Robin Gud Shoot'), ('AYGOQCHI_SPY', 'Aygoqchi Spy'), ('KONCHI_MINE', 'Konchi Mine'), ('FOTOPARATCHI_SNAP', 'Fotoparatchi Snap'), ('QAROQCHI_ROB', 'Qaroqchi Rob'), ('LABORANT_ACTION', 'Laborant Action'), ('QORBOBO_GIFT', 'Qorbobo Gift'), ('OSHPAZ_FEED', 'Oshpaz Feed'), ('SKIP', 'Skip / Pass')], max_length=50),
        ),
    ]
