# Generated by Django 5.2.15 on 2026-08-24 19:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('actor', models.CharField(default='SuperAdmin', max_length=150)),
                ('target', models.CharField(blank=True, default='', max_length=200)),
                ('details', models.TextField(blank=True, default='')),
                ('ip_address', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Loglar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotSystemText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, help_text='Texnik kalit (masalan: night_start_msg)', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('LOBBY', "Lobby & O'yin Yaratish"), ('NIGHT', 'Tun Bosqichi & Rollar'), ('DAWN', "Tong & O'lim E'loni"), ('VOTING', 'Kun & Ovoz Berish'), ('PROFILE', 'Profil & Balans'), ('SHOP', "Do'kon & Narxlar"), ('BUTTONS', 'Tugmalar (Buttons)'), ('GENERAL', 'Umumiy Xabarlar')], db_index=True, default='GENERAL', max_length=30)),
                ('title', models.CharField(help_text='Admin uchun tushunarli nom', max_length=200)),
                ('content_uz', models.TextField(help_text="O'zbek tilidagi matn")),
                ('content_ru', models.TextField(blank=True, default='', help_text='Rus tilidagi matn (ixtiyoriy)')),
                ('content_en', models.TextField(blank=True, default='', help_text='Ingliz tilidagi matn (ixtiyoriy)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bot Tizim Matni',
                'verbose_name_plural': 'Bot Tizim Matnlari',
                'ordering': ['category', 'key'],
            },
        ),
    ]
