# Generated by Django 5.2.15 on 2026-08-24 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="E'lon sarlavhasi (ichki foydalanish uchun)", max_length=200)),
                ('content', models.TextField(help_text="Xabar matni (HTML teglari qo'llab-quvvatlanadi)")),
                ('target_audience', models.CharField(choices=[('ALL_PLAYERS', "Barcha botlarning barcha o'yinchilariga"), ('BOT_OWNERS', 'Faqat botlarning haqiqiy egalariga')], default='ALL_PLAYERS', max_length=30)),
                ('photo_url', models.URLField(blank=True, default='', help_text='Rasm havolasi (ixtiyoriy)', max_length=500)),
                ('button_text', models.CharField(blank=True, default='', help_text='Tugma matni (ixtiyoriy)', max_length=100)),
                ('button_url', models.URLField(blank=True, default='', help_text='Tugma havolasi (ixtiyoriy)', max_length=500)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_success', models.PositiveIntegerField(default=0)),
                ('sent_failed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('IN_PROGRESS', 'Yuborilmoqda'), ('COMPLETED', 'Yakunlandi'), ('FAILED', 'Xatolik')], default='PENDING', max_length=20)),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('group', models.CharField(choices=[('TIMINGS', "O'yin Vaqtlari (Durations)"), ('PRICES', "Do'kon Mahsulotlari Narxlari"), ('REWARDS', 'Mukofotlar & Bonuslar')], db_index=True, default='TIMINGS', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('value', models.CharField(help_text='Qiymat (masalan: 60, 300, 2)', max_length=100)),
                ('unit', models.CharField(blank=True, default='', help_text='Birlik (sekund, 💶, 💎)', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': "O'yin Sozlamasi",
                'verbose_name_plural': "O'yin Sozlamalari",
                'ordering': ['group', 'key'],
            },
        ),
        migrations.AlterField(
            model_name='botsystemtext',
            name='category',
            field=models.CharField(choices=[('LOBBY', "Lobby & O'yin Yaratish"), ('NIGHT', 'Tun Bosqichi & Rollar'), ('DAWN', "Tong & O'lim E'loni"), ('VOTING', 'Kun & Ovoz Berish'), ('PROFILE', 'Profil & Balans'), ('SHOP', "Do'kon & Narxlar"), ('BUTTONS', 'Tugmalar (Buttons)'), ('GIFS', 'GIF Animatsiyalari'), ('GENERAL', 'Umumiy Xabarlar')], db_index=True, default='GENERAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='botsystemtext',
            name='content_uz',
            field=models.TextField(help_text="O'zbek tilidagi matn yoki GIF URL"),
        ),
    ]
