# Generated by Django 5.2.15 on 2026-08-24 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_broadcastmessage_gamesetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('reward_type', models.CharField(choices=[('COINS', '💶 Dollar'), ('DIAMONDS', '💎 Olmos'), ('VIP_DAYS', '👑 VIP Kunlar')], default='COINS', max_length=20)),
                ('reward_amount', models.PositiveIntegerField(default=100)),
                ('max_uses', models.PositiveIntegerField(default=100)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('used_by', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Promokod',
                'verbose_name_plural': 'Promokodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='botsystemtext',
            name='category',
            field=models.CharField(choices=[('FATHER_BUTTONS', 'Father Bot Tugmalari'), ('CHILD_BUTTONS', "O'yin Boti Tugmalari"), ('ACTION_BUTTONS', 'Harakat Tugmalari (Tun/Kun/Ovoz)'), ('LOBBY', "Lobby & O'yin Yaratish"), ('NIGHT', 'Tun Bosqichi & Rollar'), ('DAWN', "Tong & O'lim E'loni"), ('VOTING', 'Kun & Ovoz Berish'), ('PROFILE', 'Profil & Balans'), ('SHOP', "Do'kon & Xaridlar"), ('GIFS', 'GIF Animatsiyalari'), ('GENERAL', 'Umumiy Xabarlar')], db_index=True, default='GENERAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='botsystemtext',
            name='content_uz',
            field=models.TextField(help_text="O'zbek tilidagi matn yoki tugma yozuvi"),
        ),
        migrations.AlterField(
            model_name='botsystemtext',
            name='key',
            field=models.CharField(db_index=True, help_text='Texnik kalit', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='button_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='button_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='title',
            field=models.CharField(help_text="E'lon sarlavhasi", max_length=200),
        ),
    ]
