# Generated by Django 5.2.15 on 2026-08-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_promocode_alter_botsystemtext_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='reward_type',
            field=models.CharField(choices=[('COINS', '💶 Dollar'), ('DIAMONDS', '💎 Olmos'), ('VIP_DAYS', '👑 VIP Kunlar'), ('HIMOYA', '🛡 Himoya qalqoni'), ('OSISH_HIMOYA', '⚖️ Osishdan himoya'), ('HUJJAT', '📁 Soxta hujjat'), ('GEROY_HIMOYA', '🔰 Geroydan himoya'), ('GEROY', '🥷 Geroy'), ('ROLE_DON', '🎭 Faol Rol: Don'), ('ROLE_KOMISSAR', '🎭 Faol Rol: Komissar'), ('ROLE_SHIFOKOR', '🎭 Faol Rol: Shifokor'), ('ROLE_CITIZEN', '🎭 Faol Rol: Tinch aholi')], default='COINS', max_length=30),
        ),
    ]
