# Generated by Django 5.2.15 on 2026-08-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_alter_promocode_reward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='reward_type',
            field=models.CharField(choices=[('COINS', '💶 Dollar'), ('DIAMONDS', '💎 Olmos'), ('VIP_DAYS', '👑 VIP Kunlar'), ('HIMOYA', '🛡 Himoya qalqoni'), ('OSISH_HIMOYA', '⚖️ Osishdan himoya'), ('HUJJAT', '📁 Soxta hujjat'), ('VAKSINA', '💉 Zombi Vaksinasi'), ('GEROY_HIMOYA', '🔰 Geroydan himoya'), ('GEROY', '🥷 Geroy'), ('ROLE_DON', '🎭 Faol Rol: Don'), ('ROLE_KOMISSAR', '🎭 Faol Rol: Komissar'), ('ROLE_SHIFOKOR', '🎭 Faol Rol: Shifokor'), ('ROLE_CITIZEN', '🎭 Faol Rol: Tinch aholi'), ('ROLE_QOTIL', '🔪 Faol Rol: Qotil'), ('ROLE_KEZUVCHI', '💃 Faol Rol: Kezuvchi'), ('ROLE_SERJANT', '👮🏼\u200d♂️ Faol Rol: Serjant'), ('ROLE_DAYDI', '🍾 Faol Rol: Daydi'), ('ROLE_ADVOKAT', '💼 Faol Rol: Advokat'), ('ROLE_SUIDSID', '🤡 Faol Rol: Suidsid'), ('ROLE_UBIYTSA', '🥷 Faol Rol: Ubiytsa'), ('ROLE_AFSUNGAR', '🧙🏼 Faol Rol: Afsungar'), ('ROLE_TUZOQCHI', '🕸 Faol Rol: Tuzoqchi'), ('ROLE_ZOMBI', '🧟 Faol Rol: Zombi'), ('ROLE_KIMYOGAR', '🧪 Faol Rol: Kimyogar'), ('ROLE_AXMOQ', '🤪 Faol Rol: Axmoq'), ('ROLE_BUQALAMUN', '🦎 Faol Rol: Buqalamun'), ('ROLE_RAIS', '🏛 Faol Rol: Rais'), ('ROLE_HAMSHIRA', '👩🏼\u200d⚕️ Faol Rol: Hamshira'), ('ROLE_JOKER', '🃏 Faol Rol: Joker')], default='COINS', max_length=30),
        ),
    ]
