# Generated by Django 5.2.15 on 2026-08-27 06:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_alter_promocode_reward_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('telegram_username', models.CharField(blank=True, max_length=150, null=True)),
                ('user_display_name', models.CharField(blank=True, default='', max_length=200)),
                ('message_text', models.TextField()),
                ('is_replied', models.BooleanField(default=False)),
                ('admin_reply', models.TextField(blank=True, default='')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Savol va Taklif',
                'verbose_name_plural': 'Savollar va Takliflar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, help_text="NULL bo'lsa barcha foydalanuvchilarga ko'rinadi", null=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'Tizim xabari'), ('ADMIN', "Admin e'loni"), ('PERSONAL', 'Shaxsiy xabar'), ('TRANSFER', "O'tkazma bildirishnomasi")], default='SYSTEM', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_by', models.CharField(default='SuperAdmin', max_length=150)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi Bildirishnomasi',
                'verbose_name_plural': 'Foydalanuvchi Bildirishnomalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='target_user_id',
            field=models.CharField(blank=True, default='', help_text='Alohida foydalanuvchi Telegram ID yoki @username', max_length=100),
        ),
        migrations.AlterField(
            model_name='botsystemtext',
            name='category',
            field=models.CharField(choices=[('FATHER_BUTTONS', 'Father Bot Tugmalari'), ('CHILD_BUTTONS', "O'yin Boti Tugmalari"), ('ACTION_BUTTONS', 'Harakat Tugmalari (Tun/Kun/Ovoz)'), ('LOBBY', "Lobby & O'yin Yaratish"), ('NIGHT', 'Tun Bosqichi & Rollar'), ('DAWN', "Tong & O'lim E'loni"), ('VOTING', 'Kun & Ovoz Berish'), ('PROFILE', 'Profil & Balans'), ('SHOP', "Do'kon & Xaridlar"), ('GIFS', 'GIF Animatsiyalari'), ('TRANSFERS', "O'tkazmalar (Pul & Olmos)"), ('GENERAL', 'Umumiy Xabarlar')], db_index=True, default='GENERAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='target_audience',
            field=models.CharField(choices=[('ALL_PLAYERS', "Barcha botlarning barcha o'yinchilariga"), ('BOT_OWNERS', 'Faqat botlarning haqiqiy egalariga'), ('SPECIFIC_USER', 'Alohida bitta foydalanuvchiga')], default='ALL_PLAYERS', max_length=30),
        ),
    ]
