# Generated by Django 5.2.15 on 2026-09-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_feedbackmessage_usernotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesetting',
            name='group',
            field=models.CharField(choices=[('TIMINGS', "O'yin Vaqtlari (Durations)"), ('PRICES', "Do'kon Mahsulotlari Narxlari"), ('HERO', 'Geroy Sozlamalari'), ('RANKS', 'Unvonlar & Darajalar'), ('REWARDS', 'Mukofotlar & Bonuslar')], db_index=True, default='TIMINGS', max_length=30),
        ),
    ]
