# Generated by Django 5.2.15 on 2026-09-09 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_botuser'),
        ('superadmin', '0007_alter_gamesetting_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='sender_bot_type',
            field=models.CharField(blank=True, default='AUTO', help_text='Yuboruvchi bot turi: AUTO, MASTER_BOT, ALL_USER_BOTS, SPECIFIC_BOT, ALL_ACTIVE_BOTS', max_length=50),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='target_bot',
            field=models.ForeignKey(blank=True, help_text='Yuborish uchun tanlangan aniq bot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='bots.bot'),
        ),
    ]
