# Generated by Django 5.2.15 on 2026-09-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_broadcastmessage_sender_bot_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsystemtext',
            name='category',
            field=models.CharField(choices=[('FATHER_BUTTONS', 'Father Bot Tugmalari'), ('CHILD_BUTTONS', "O'yin Boti Tugmalari"), ('ACTION_BUTTONS', 'Harakat Tugmalari (Tun/Kun/Ovoz)'), ('LOBBY', "Lobby & O'yin Yaratish"), ('NIGHT', 'Tun Bosqichi & Rollar'), ('HERO', 'Geroy & Zarbalar'), ('DAWN', "Tong & O'lim E'loni"), ('VOTING', 'Kun & Ovoz Berish'), ('PROFILE', 'Profil & Balans'), ('SHOP', "Do'kon & Xaridlar"), ('GIFS', 'GIF Animatsiyalari'), ('TRANSFERS', "O'tkazmalar (Pul & Olmos)"), ('GENERAL', 'Umumiy Xabarlar')], db_index=True, default='GENERAL', max_length=30),
        ),
    ]
