# Generated by Django 5.2.15 on 2026-09-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_alter_botsystemtext_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='photo_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='target_audience',
            field=models.CharField(choices=[('CHANNEL', '📢 Rasmiy kanal (@MafiaBotFather)'), ('ALL_PLAYERS', "👥 Barcha botlarning barcha o'yinchilariga"), ('BOT_OWNERS', '👑 Faqat botlarning haqiqiy egalariga'), ('SPECIFIC_USER', '🎯 Alohida bitta foydalanuvchiga'), ('SPECIFIC_CHANNEL', '📢 Boshqa kanal yoki guruhga (ID/@username)')], default='CHANNEL', max_length=30),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='target_user_id',
            field=models.CharField(blank=True, default='', help_text='Alohida foydalanuvchi/kanal Telegram ID yoki @username', max_length=100),
        ),
    ]
