# Generated by Django 5.2.15 on 2026-08-17 20:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('rate_to_usd', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=14)),
                ('name', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('icon', models.CharField(default='💎', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🎁', max_length=20)),
                ('item_type', models.CharField(choices=[('DIAMONDS_PACK', 'Diamonds Pack'), ('VIP_PACK', 'VIP Subscription Pack'), ('COSMETIC', 'Cosmetic / Theme'), ('BADGE', 'Profile Badge'), ('ROLE', 'Special Role'), ('BONUS', 'Game Bonus'), ('GIFT_ITEM', 'Gift Item')], db_index=True, max_length=30)),
                ('price_diamonds', models.PositiveIntegerField(default=0)),
                ('price_money_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('diamond_amount', models.PositiveIntegerField(default=0, help_text='Amount of diamonds credited if item is DIAMONDS_PACK')),
                ('vip_days', models.PositiveIntegerField(default=0, help_text='Number of VIP days granted if item is VIP_PACK')),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='economy.marketplacecategory')),
            ],
            options={
                'ordering': ['category__order', 'price_diamonds', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GiftRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('recipient_telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_gifts', to=settings.AUTH_USER_MODEL)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_gifts', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='economy.marketplaceitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('order_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_uzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('diamonds_to_credit', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(default='P2P_CARD', max_length=50)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_REVIEW', max_length=20)),
                ('receipt_reference', models.CharField(blank=True, max_length=255)),
                ('receipt_image_url', models.URLField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency_paid', models.CharField(choices=[('MONEY', 'Money ($)'), ('DIAMONDS', 'Diamonds (💎)'), ('COINS', 'Coins (🪙)')], max_length=20)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='economy.marketplaceitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VIPSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('vip_level', models.CharField(choices=[('BRONZE', 'VIP Bronze 🥉'), ('SILVER', 'VIP Silver 🥈'), ('GOLD', 'VIP Gold 🥇'), ('DIAMOND', 'VIP Diamond 💎')], default='GOLD', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vip_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expires_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('money', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('diamonds', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economy.marketplaceitem')),
            ],
            options={
                'ordering': ['-acquired_at'],
                'unique_together': {('telegram_id', 'item'), ('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tx_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('PURCHASE', 'Purchase'), ('REWARD', 'Game Reward'), ('GIFT', 'Gift'), ('REFUND', 'Refund'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('DEPOSIT', 'Deposit / Payment')], db_index=True, max_length=30)),
                ('currency', models.CharField(choices=[('MONEY', 'Money ($)'), ('DIAMONDS', 'Diamonds (💎)'), ('COINS', 'Coins (🪙)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='economy.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='economy_wal_wallet__5215ff_idx'), models.Index(fields=['tx_type', 'created_at'], name='economy_wal_tx_type_6b9bf5_idx')],
            },
        ),
    ]
