# Generated by Django 5.2.15 on 2026-09-05 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerHero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('owner_name', models.CharField(default="O'yinchi", max_length=100)),
                ('name', models.CharField(default='Mening Geroyim', max_length=100)),
                ('level', models.PositiveIntegerField(default=1)),
                ('score', models.PositiveIntegerField(default=0)),
                ('charges', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('current_defense', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-level', '-score'],
            },
        ),
    ]
