# Generated by Django 5.2.15 on 2026-09-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_playerhero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerhero',
            name='charges',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
