# Generated by Django 5.2.15 on 2026-09-09 17:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_alter_playerhero_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveawayDrop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_telegram_id', models.BigIntegerField(db_index=True)),
                ('sender_name', models.CharField(default='', max_length=255)),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('MONEY', 'Money ($)'), ('DIAMONDS', 'Diamonds (💎)'), ('COINS', 'Coins (🪙)')], default='DIAMONDS', max_length=20)),
                ('total_amount', models.PositiveIntegerField(default=1)),
                ('claimed_amount', models.PositiveIntegerField(default=0)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiveawayClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_user_id', models.BigIntegerField(db_index=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='economy.giveawaydrop')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('drop', 'telegram_user_id')},
            },
        ),
    ]
